# -*- coding: utf-8 -*-
"""python calculator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LkMyN4tKcTwevTHWpstozEYaf-Dnic0l
"""

# passo 1 solicitar entrada dos usuario
 operation = input('''
 Please type in the math operation you would like to complete:
+ for addition
- for subtraction
* for multiplication
/ for division
''')
num1 = input('enter your first number: ' )
num2 = input('enter your second number:')

num1 = int( input( 'enter your first number: ' ) )
num2 = int( input( 'enter your second number: ' ) )

#passo 2 adicionando operadores
num1 = int( input( 'enter your first number: ' ) )
num2 = int( input( 'enter your second number: ' ) )
print(num1 + num2)

num1 = int( input( ' enter your first number: ' ) )
num2 = int( input( ' enter your second number: ' ) )
print (' {}+ {} = '. format(num1, num2 ))
print( num1 + num2)

def calculate():
    operation = input('''
Please type in the math operation you would like to complete:
+ for addition
- for subtraction
* for multiplication
/ for division
''')

number_1 = int(input('Enter your first number: '))
number_2 = int(input('Enter your second number: '))

if operation == '+':
    print('{} + {} = '.format(number_1, number_2))
    print(number_1 + number_2)

elif operation == '-':
    print('{} - {} = '.format(number_1, number_2))
    print(number_1 - number_2)

elif operation == '*':
    print('{} * {} = '.format(number_1, number_2))
    print(number_1 * number_2)

elif operation == '/':
    print('{} / {} = '.format(number_1, number_2))
    print(number_1 / number_2)

else:
    print('You have not typed a valid operator, please run the program again.')
   # Add again() function to calculate() function
    again()

def again():
    calc_again = input('''
Do you want to calculate again?
Please type Y for YES or N for NO.
''')

    if calc_again.upper() == 'Y':
        calculate()
    elif calc_again.upper() == 'N':
        print('See you later.')
    else:
        again()

calculate()

...
# Define again() function to ask user if they want to use the calculator again
def again():

    # Take input from user
    calc_again = input('''
Do you want to calculate again?
Please type Y for YES or N for NO.
''')

    # If user types Y, run the calculate() function
    if calc_again == 'Y':
        calculate()

    # If user types N, say good-bye to the user and end the program
    elif calc_again == 'N':
        print('See you later.')

    # If user types another key, run the function again
    else:
        again()

# Call calculate() outside of the function
calculate()